Repository VectorInstitute/mmlearn, pull requests merged in 2024-09, with the labels that each got.

#7 Update dataloader sampler configs and instantiation
  mmlearn/cli/_instantiators.py
  mmlearn/conf/__init__.py
Labels: bug, refactor

#8 Add BIOSCAN-CLIP project
  mmlearn/datasets/core/modalities.py
  mmlearn/modules/encoders/clip_encoders.py
  mmlearn/modules/encoders/hf_text_encoders.py
  poetry.lock
  projects/bioscan_clip/README.md
  projects/bioscan_clip/configs/__init__.py
  projects/bioscan_clip/configs/experiment/bioscan_1m.yaml
  projects/bioscan_clip/dataset.py
  projects/bioscan_clip/dna_tokenizer.py
  projects/bioscan_clip/encoders.py
  projects/bioscan_clip/eval_task.py
  projects/bioscan_clip/requirements.txt
  pyproject.toml
Labels: enhancement

#12 Fix usage of optional dependencies
  mmlearn/conf/__init__.py
  mmlearn/datasets/librispeech.py
  mmlearn/datasets/nyuv2.py
  mmlearn/datasets/sunrgbd.py
  poetry.lock
  pyproject.toml
Labels: bug

#14 Fix handling of `attention_mask` in encoders
  mmlearn/modules/encoders/clip_encoders.py
  mmlearn/modules/encoders/hf_text_encoders.py
  projects/bioscan_clip/encoders.py
Labels: bug

#18 Move timm vit encoder from bioscan project into modules
  mmlearn/modules/encoders/vision.py
  projects/bioscan_clip/configs/__init__.py
  projects/bioscan_clip/encoders.py
Labels: refactor

#19 Refactor datasets and update dependencies
  poetry.lock
  projects/med_benchmarking/datasets/mimiciv_cxr.py
  projects/med_benchmarking/datasets/pmcoa.py
  projects/med_benchmarking/datasets/quilt.py
  projects/med_benchmarking/datasets/roco.py
  projects/med_benchmarking/requirements.txt
  pyproject.toml
Labels: refactor

#16 Add data2vec loss class, rename modules
  README.md
  mmlearn/modules/encoders/__init__.py
  mmlearn/modules/encoders/clip.py
  mmlearn/modules/encoders/text.py
  mmlearn/modules/losses/__init__.py
  mmlearn/modules/losses/contrastive.py
  mmlearn/modules/losses/data2vec.py
  projects/bioscan_clip/configs/__init__.py
Labels: enhancement, refactor
